import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Saksham Gupta",
  description: "Generated by create next app",
  openGraph: {
    type: "website",
    url: "https://www.skshmgpt.tech",
    title: "Saksham Gupta",
    description: "Saksham's Portfolio",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.className} ${geistMono.variable} antialiased bg-black/94`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
